service: start-war-api
app: start-war-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}
  apiGateway:
    shouldStartNameWithService: true
  region: ${opt:region}

package:
  exclude:
    - scripts/**
    - node_modules/**
    - layers/**
    - package.json
    - package-lock.json
    - "*.md"
    - "env.*"
    - scannerwork/
    - sonar-project.properties
    - test/**
    - src/**
    - Dockerfile
    - .tmp/**
    - coverage/**

layers:
  StartWarLayer:
    name: ${self:service}-${self:provider.stage}-dependencies
    path: layers
    description: "START-WAR-SOS-API"
    compatibleRuntimes:
      - nodejs18.x
    package:
      exclude:
        - "!nodejs/node_modules/**"

functions:
  paginate:
    handler: dist/src/shared/infrastructure/lambda/paginate.handler
    timeout: 30
    memorySize: 256
    architecture: arm64
    layers:
      - { Ref: StartWarLayerLambdaLayer }
    events:
      - http:
          path: /films/paginate
          method: get
          cors:
            origin: "*"
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Amz-Security-Token
            allowCredentials: false

  create:
    handler: dist/src/shared/infrastructure/lambda/create.handler
    timeout: 30
    memorySize: 256
    architecture: arm64
    layers:
      - { Ref: StartWarLayerLambdaLayer }
    events:
      - http:
          path: /films/create
          method: post
          cors:
            origin: "*"
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Amz-Security-Token
            allowCredentials: false


  swagger:
    handler: dist/src/shared/infrastructure/lambda/swagger.handler
    timeout: 30
    memorySize: 256
    architecture: arm64
    events:
      - http:
          path: /swagger
          method: get
      - http:
          path: /swagger.json
          method: get
plugins:
  - serverless-offline

