// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Api de Start War",
    "version": "1"
  },
  "paths": {
    "/films/paginate": {
      "get": {
        "summary": "End para paginar peliculas",
        "description": "Lista las peliculas que coinciden con la query de la busqueda",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "description": "Valor de la búsqueda",
            "required": false
          },
          {
            "name": "page",
            "in": "query",
            "description": "Número de página",
            "required": false,
            "type": "integer"
          },
          {
            "name": "perPage",
            "in": "query",
            "description": "Número de resultados por página",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Film"
              }
            }
          }
        }
      }
    },
    "/films/create": {
      "post": {
        "summary": "Crea una película",
        "parameters": [
          {
            "name": "film",
            "in": "body",
            "description": "Objeto de Pelílula que se debe añadir",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Film"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "La pelicula ha sido creado"
          }
        }
      }
    },
    "/{proxy+}": {
      "any": {
        "summary": "main",
        "description": "",
        "operationId": "main.any./{proxy+}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proxy+",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Film": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "uniqueItems": true,
          "example": "123e4567-e89b-12d3-a456-426614174000"
        },
        "titulo": {
          "type": "string",
          "example": "Star Wars: Episodio IV - Una nueva esperanza"
        },
        "episodio": {
          "type": "number",
          "example": 4
        },
        "apertura": {
          "type": "string",
          "example": "Hace mucho tiempo en una galaxia muy, muy lejana..."
        },
        "director": {
          "type": "string",
          "example": "George Lucas"
        },
        "creado": {
          "type": "date"
        },
        "editado": {
          "type": "date"
        }
      },
      "required": [
        "id",
        "titulo",
        "episodio",
        "director"
      ]
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http",
    "https"
  ]
};